FROM ubuntu:23.10
RUN apt-get update && apt-get install curl -y

WORKDIR /provision
COPY ./mongo-sink.json ./mongo-sink.json

ENTRYPOINT curl -X POST -H "Content-Type: application/json" -d @mongo-sink.json http://kconnect:8083/connectors
