version: "3"
services:
  zookeeper:
    image: 'zookeeper:3.9.0'
    container_name: zookeeper
    ports:
      - '2181:2181'
    networks: 
      - kafka_network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  kafka:
    image: 'vehicle-tracker-kafka:latest'
    container_name: kafka
    ports:
      - '9094:9094'
    networks: 
      - kafka_network
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://:9092,EXTERNAL_SAME_HOST://:9093,EXTERNAL_DIFFERENT_HOST://:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:9093,EXTERNAL_DIFFERENT_HOST://192.168.33.10:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT,EXTERNAL_DIFFERENT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
      
networks:
  kafka_network:
    name: kafka_net
