version: "3"
services:
  mongo:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mongo 
    ports:
      - '27017:27017'
    networks: 
      - mongo_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: mongod --replSet rs0 --bind_ip localhost,mongo --keyFile /opt/rs-keyfile
    healthcheck:
      test: mongosh -u root -p root --eval 'print('')' || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10   

  mongo-init:
    build:
      context: .
      dockerfile: Dockerfile-mongo-init
    container_name: mongo-init
    networks:
      - mongo_network
    depends_on:
      mongo:
        condition: service_healthy
     
      
networks:
  mongo_network:  
    name: mongo-net
    driver: bridge
